import { StructureDef, UnitDef, StructureType, UnitType, Faction } from './types';

export const STRUCTURE_DEFS: Record<StructureType, StructureDef> = {
  conyard: {
    type: 'conyard',
    name: 'Centro de Mando (ConYard)',
    category: 'structures',
    cost: 2500,
    buildTime: 20,
    hp: 4000,
    powerOut: 50,
    powerIn: 0,
    width: 96,
    height: 96,
    description: 'Estructura principal de mando. Permite la construcción de bases y provee radar táctico.',
  },
  powerplant: {
    type: 'powerplant',
    name: 'Central Eléctrica',
    category: 'structures',
    cost: 600,
    buildTime: 7,
    hp: 900,
    powerOut: 200,
    powerIn: 0,
    width: 64,
    height: 64,
    prereq: ['conyard'],
    description: 'Genera 200 MW de energía para alimentar defensas, fábricas y radares.',
  },
  refinery: {
    type: 'refinery',
    name: 'Refinería de Tiberio',
    category: 'structures',
    cost: 1800,
    buildTime: 14,
    hp: 2400,
    powerOut: 0,
    powerIn: 50,
    width: 96,
    height: 80,
    prereq: ['powerplant'],
    description: 'Procesa el cristal de Tiberio en créditos. Incluye 1 Cosechador blindado gratuito.',
  },
  barracks: {
    type: 'barracks',
    name: 'Barracones Militares',
    category: 'structures',
    cost: 500,
    buildTime: 8,
    hp: 1200,
    powerOut: 0,
    powerIn: 25,
    width: 64,
    height: 64,
    prereq: ['powerplant'],
    description: 'Permite reclutar y entrenar escuadras de infantería ligera y de asalto.',
  },
  warfactory: {
    type: 'warfactory',
    name: 'Fábrica de Armamento',
    category: 'structures',
    cost: 2000,
    buildTime: 16,
    hp: 2800,
    powerOut: 0,
    powerIn: 60,
    width: 112,
    height: 96,
    prereq: ['refinery'],
    description: 'Construye vehículos blindados de combate pesado, cosechadores y aeronaves.',
  },
  turret: {
    type: 'turret',
    name: 'Torreta Defensiva',
    category: 'defenses',
    cost: 700,
    buildTime: 9,
    hp: 1400,
    powerOut: 0,
    powerIn: 30,
    width: 48,
    height: 48,
    prereq: ['barracks'],
    weapon: {
      damage: 32,
      range: 220,
      rateOfFire: 1.4,
      targetsAir: false,
      type: 'bullet',
    },
    description: 'Defensa perimetral automatizada eficaz contra infantería y blindados ligeros.',
  },
  aaturret: {
    type: 'aaturret',
    name: 'Batería Misiles Antiaéreos',
    category: 'defenses',
    cost: 900,
    buildTime: 10,
    hp: 1200,
    powerOut: 0,
    powerIn: 40,
    width: 48,
    height: 48,
    prereq: ['barracks'],
    weapon: {
      damage: 65,
      range: 280,
      rateOfFire: 0.9,
      targetsAir: true,
      type: 'missile',
    },
    description: 'Defensa con misiles guiados capaz de derribar aeronaves y hostigar tanques.',
  },
  techlab: {
    type: 'techlab',
    name: 'Centro Tecnológico',
    category: 'structures',
    cost: 3000,
    buildTime: 22,
    hp: 2200,
    powerOut: 0,
    powerIn: 90,
    width: 80,
    height: 80,
    prereq: ['warfactory'],
    description: 'Desbloquea unidades pesadas de élite (Zone Troopers / Caminantes) y superarmas.',
  },
  superweapon: {
    type: 'superweapon',
    name: 'Enlace Cañón de Iones / Templo',
    category: 'structures',
    cost: 4500,
    buildTime: 30,
    hp: 4500,
    powerOut: 0,
    powerIn: 150,
    width: 112,
    height: 112,
    prereq: ['techlab'],
    description: 'Permite disparar el rayo orbital Cañón de Iones (GDI) o el Misil Nuclear (Nod).',
  },
};

export const UNIT_DEFS: Record<UnitType, UnitDef> = {
  harvester: {
    type: 'harvester',
    name: 'Cosechador de Tiberio',
    category: 'vehicles',
    cost: 1200,
    buildTime: 12,
    hp: 2200,
    speed: 95,
    range: 0,
    damage: 0,
    rateOfFire: 0,
    damageType: 'bullet',
    isAir: false,
    canTargetAir: false,
    size: 34,
    prereq: ['refinery', 'warfactory'],
    description: 'Vehículo blindado pesado que recolecta cristal de Tiberio y lo entrega a la refinería.',
  },
  rifleman: {
    type: 'rifleman',
    name: 'Escuadra de Fusileros',
    category: 'infantry',
    cost: 200,
    buildTime: 4,
    hp: 260,
    speed: 120,
    range: 150,
    damage: 14,
    rateOfFire: 2.2,
    damageType: 'bullet',
    isAir: false,
    canTargetAir: false,
    size: 16,
    prereq: ['barracks'],
    description: 'Infantería ligera con rifle de asalto. Excelente contra tropas a pie y exploración rápida.',
  },
  missile: {
    type: 'missile',
    name: 'Escuadra Lanzamisiles',
    category: 'infantry',
    cost: 350,
    buildTime: 6,
    hp: 280,
    speed: 105,
    range: 220,
    damage: 42,
    rateOfFire: 0.8,
    damageType: 'rocket',
    isAir: false,
    canTargetAir: true,
    size: 18,
    prereq: ['barracks'],
    description: 'Infantería equipada con cohetes antiblindaje y capacidad antiaérea.',
  },
  zone_trooper: {
    type: 'zone_trooper',
    name: 'Soldado de Zona / Mano Negra',
    category: 'infantry',
    cost: 800,
    buildTime: 11,
    hp: 750,
    speed: 95,
    range: 190,
    damage: 75,
    rateOfFire: 1.1,
    damageType: 'laser',
    isAir: false,
    canTargetAir: false,
    size: 22,
    prereq: ['barracks', 'techlab'],
    description: 'Infantería pesada exoesqueleto con cañones electromagnéticos y alta armadura.',
  },
  engineer: {
    type: 'engineer',
    name: 'Ingeniero de Combate',
    category: 'infantry',
    cost: 500,
    buildTime: 7,
    hp: 320,
    speed: 110,
    range: 65,
    damage: 0,
    rateOfFire: 0,
    damageType: 'laser',
    isAir: false,
    canTargetAir: false,
    size: 18,
    prereq: ['barracks'],
    description: 'Especialista en ingeniería. Repara edificios aliados, ocupa estructuras enemigas capturando sus armas/recursos, y al alcanzar Nivel 2 (Élite) puede relocalizar y mover edificios.',
  },
  tank: {
    type: 'tank',
    name: 'Tanque Predator / Scorpion',
    category: 'vehicles',
    cost: 1000,
    buildTime: 10,
    hp: 1500,
    speed: 135,
    range: 200,
    damage: 85,
    rateOfFire: 0.9,
    damageType: 'cannon',
    isAir: false,
    canTargetAir: false,
    size: 32,
    prereq: ['warfactory'],
    description: 'Tanque de combate principal con torreta giratoria y cañón de 120mm.',
  },
  apc: {
    type: 'apc',
    name: 'Transporte Blindado / Buggy',
    category: 'vehicles',
    cost: 650,
    buildTime: 7,
    hp: 850,
    speed: 175,
    range: 160,
    damage: 28,
    rateOfFire: 2.5,
    damageType: 'bullet',
    isAir: false,
    canTargetAir: true,
    size: 26,
    prereq: ['warfactory'],
    description: 'Vehículo ligero de asalto rápido armado con cañón rotativo antiaéreo.',
  },
  aircraft: {
    type: 'aircraft',
    name: 'Aeronave Orca / Venom',
    category: 'vehicles',
    cost: 1300,
    buildTime: 13,
    hp: 950,
    speed: 195,
    range: 220,
    damage: 60,
    rateOfFire: 1.2,
    damageType: 'rocket',
    isAir: true,
    canTargetAir: true,
    size: 28,
    prereq: ['warfactory'],
    description: 'Caza artillado VTOL. Vuela sobre cualquier terreno hostigando blancos terrestres y aéreos.',
  },
  walker: {
    type: 'walker',
    name: 'Caminante Juggernaut / Avatar',
    category: 'vehicles',
    cost: 2400,
    buildTime: 22,
    hp: 3200,
    speed: 80,
    range: 300,
    damage: 160,
    rateOfFire: 0.55,
    damageType: 'cannon',
    isAir: false,
    canTargetAir: false,
    size: 44,
    prereq: ['warfactory', 'techlab'],
    description: 'Arma bípeda colosal de asedio masivo capaz de pulverizar bases enemigas a larga distancia.',
  },
};

export interface MapPreset {
  id: string;
  name: string;
  description: string;
  width: number;
  height: number;
  playerStart: { x: number; y: number };
  enemyStart: { x: number; y: number };
  tiberiumPatches: { x: number; y: number; type: 'green' | 'blue'; amount: number }[];
  terrainObstacles: { x: number; y: number; width: number; height: number; type: 'rock' | 'ruins' | 'crater' }[];
}

export const MAP_PRESETS: Record<string, MapPreset> = {
  wasteland: {
    id: 'wasteland',
    name: 'Zona Roja: Tierras Yermas',
    description: 'Páramo altamente contaminado con vastos yacimientos de Tiberio verde y azul en el centro.',
    width: 2400,
    height: 2400,
    playerStart: { x: 380, y: 380 },
    enemyStart: { x: 2020, y: 2020 },
    tiberiumPatches: [
      // Near player base
      { x: 550, y: 300, type: 'green', amount: 8000 },
      { x: 300, y: 620, type: 'green', amount: 8000 },
      // Central hotzone
      { x: 1200, y: 1200, type: 'blue', amount: 16000 },
      { x: 950, y: 1350, type: 'green', amount: 12000 },
      { x: 1450, y: 1050, type: 'green', amount: 12000 },
      // Near enemy base
      { x: 1850, y: 2100, type: 'green', amount: 8000 },
      { x: 2100, y: 1780, type: 'green', amount: 8000 },
    ],
    terrainObstacles: [
      { x: 800, y: 600, width: 140, height: 120, type: 'rock' },
      { x: 1600, y: 1800, width: 140, height: 120, type: 'rock' },
      { x: 1100, y: 700, width: 180, height: 140, type: 'crater' },
      { x: 1300, y: 1700, width: 180, height: 140, type: 'crater' },
      { x: 700, y: 1500, width: 200, height: 160, type: 'ruins' },
      { x: 1700, y: 900, width: 200, height: 160, type: 'ruins' },
    ],
  },
  sarajevo: {
    id: 'sarajevo',
    name: 'Sector Urbano: Ruinas de Sarajevo',
    description: 'Choke points urbanos, restos industriales y campos de Tiberio en avenidas bloqueadas.',
    width: 2400,
    height: 2400,
    playerStart: { x: 400, y: 2000 },
    enemyStart: { x: 2000, y: 400 },
    tiberiumPatches: [
      { x: 650, y: 1900, type: 'green', amount: 9000 },
      { x: 300, y: 1700, type: 'green', amount: 7000 },
      { x: 1200, y: 1200, type: 'blue', amount: 18000 },
      { x: 1750, y: 500, type: 'green', amount: 9000 },
      { x: 2100, y: 700, type: 'green', amount: 7000 },
    ],
    terrainObstacles: [
      { x: 1000, y: 1100, width: 220, height: 140, type: 'ruins' },
      { x: 1400, y: 1300, width: 220, height: 140, type: 'ruins' },
      { x: 700, y: 800, width: 160, height: 160, type: 'rock' },
      { x: 1700, y: 1600, width: 160, height: 160, type: 'rock' },
    ],
  },
  yellowzone: {
    id: 'yellowzone',
    name: 'Oasis Zona Amarilla',
    description: 'Terreno desértico con colinas y dos grandes reservas de cristales en los flancos.',
    width: 2400,
    height: 2400,
    playerStart: { x: 1200, y: 350 },
    enemyStart: { x: 1200, y: 2050 },
    tiberiumPatches: [
      { x: 500, y: 1200, type: 'blue', amount: 15000 },
      { x: 1900, y: 1200, type: 'green', amount: 15000 },
      { x: 1000, y: 550, type: 'green', amount: 8000 },
      { x: 1400, y: 550, type: 'green', amount: 8000 },
      { x: 1000, y: 1850, type: 'green', amount: 8000 },
      { x: 1400, y: 1850, type: 'green', amount: 8000 },
    ],
    terrainObstacles: [
      { x: 900, y: 1200, width: 200, height: 180, type: 'rock' },
      { x: 1500, y: 1200, width: 200, height: 180, type: 'rock' },
      { x: 1200, y: 900, width: 160, height: 120, type: 'crater' },
      { x: 1200, y: 1500, width: 160, height: 120, type: 'crater' },
    ],
  },
};

export const FACTION_INFO: Record<Faction, { name: string; motto: string; color: string; accent: string; superweaponName: string; superweaponDesc: string }> = {
  gdi: {
    name: 'Iniciativa de Defensa Global (GDI)',
    motto: 'Por la paz y la supervivencia de la Tierra',
    color: '#eab308', // gold/yellow
    accent: '#3b82f6', // blue
    superweaponName: 'Cañón de Iones Orbital',
    superweaponDesc: 'Rayo energético de fusión disparado desde un satélite orbital con devastador poder destructivo concentrado.',
  },
  nod: {
    name: 'Hermandad de Nod',
    motto: 'Paz a través del poder - ¡Kane Vive!',
    color: '#ef4444', // crimson red
    accent: '#18181b', // dark charcoal
    superweaponName: 'Misil Nuclear Táctico',
    superweaponDesc: 'Ojiva atómica de alto rendimiento lanzada desde el Templo de Nod que pulveriza un amplio sector.',
  },
};

/**
 * Determina la cantidad requerida de Ingenieros Nivel 2 (Élite) necesarios para mover una estructura según su tamaño y peso.
 */
export function getRequiredEngineersToMove(type: StructureType): number {
  switch (type) {
    case 'turret':
    case 'aaturret':
      return 1; // 48x48
    case 'powerplant':
    case 'barracks':
      return 2; // 64x64
    case 'refinery':
    case 'techlab':
      return 3; // 80x80 a 96x80
    case 'conyard':
    case 'warfactory':
    case 'superweapon':
      return 4; // 96x96 a 112x112
    default:
      return 2;
  }
}
